# Generated by Django 4.2.6 on 2023-11-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_shop', '0002_alter_order_order_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
