# Generated by Django 4.2.6 on 2023-11-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_shop', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/no_image.png', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
