# Generated by Django 4.2.6 on 2023-11-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_shop', '0008_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
