# Generated by Django 4.2.6 on 2023-11-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_shop', '0009_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count', models.IntegerField()),
                ('publication', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='myapp_shop.productnew'),
        ),
    ]
