# Generated by Django 4.2.6 on 2023-11-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_shop', '0010_productnew_delete_product_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnew',
            name='publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
