# Generated by Django 4.2.6 on 2023-11-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_shop', '0011_alter_productnew_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnew',
            name='publication',
            field=models.DateField(),
        ),
    ]
