# Generated by Django 4.2.6 on 2023-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(default='2023-6-20'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='category', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication',
            field=models.DateField(auto_now_add=True),
        ),
    ]
